import { deviceSchema, type Device } from "./model";

// Human-verified manufacturer snapshot, not live prices or HMS integration claims.
// Null is unknown, never zero. False flags mean not positively verified for this row.
const verified = "2026-09-08T00:00:00Z";
function device(input: Pick<Device, "brand" | "model" | "category" | "source_urls" | "editorial_note" | "metrics_supported"> & Partial<Device>): Device {
  return deviceSchema.parse({ price_inr: null, price_usd: null, price_gbp: null, price_aed: null, battery_days: null,
    has_ecg: false, has_skin_temp: false, has_spo2: false, has_hrv: false, has_screen: false,
    subscription_required: false, subscription_cost: null, last_verified_at: verified, ...input });
}
const appleSources = ["https://www.apple.com/watch/compare/", "https://www.apple.com/us/shop/goto/buy_watch", "https://www.apple.com/in/shop/buy-watch", "https://www.apple.com/uk/shop/buy-watch", "https://www.apple.com/ae/shop/buy-watch"];
const googleVitals = "https://support.google.com/googlehealth/answer/14236917?hl=en";
const garminComparison = "https://www.garmin.com/en-US/compare/?compareProduct=1462801&compareProduct=1614061&compareProduct=851039";
export const catalog: Device[] = [
  device({ brand: "Apple", model: "Watch SE 3 (GPS)", category: "watch", price_inr: 25900, price_usd: 249, price_gbp: 219, price_aed: 999,
    battery_days: 0.75, has_screen: true, has_skin_temp: true, has_hrv: true, metrics_supported: ["heart_rate", "resting_heart_rate", "skin_temperature", "steps", "sleep_duration"], source_urls: appleSources,
    editorial_note: "Entry iPhone watch; up to 18 hours. Apple HRV is SDNN, not the RMSSD series HMS accepts." }),
  device({ brand: "Apple", model: "Watch Series 11 (GPS)", category: "watch", price_inr: 46900, price_usd: 399, price_gbp: 369, price_aed: 1599,
    battery_days: 1, has_screen: true, has_skin_temp: true, has_hrv: true, has_spo2: true, has_ecg: true,
    metrics_supported: ["heart_rate", "resting_heart_rate", "skin_temperature", "spo2", "steps", "sleep_duration"], source_urls: appleSources,
    editorial_note: "iPhone-only everyday watch; up to 24 hours. ECG and blood-oxygen availability vary by country; Apple HRV is SDNN." }),
  device({ brand: "Apple", model: "Watch Ultra 3", category: "watch", price_inr: 89900, price_usd: 700, price_gbp: 650, price_aed: 2800,
    battery_days: 1.75, has_screen: true, has_skin_temp: true, has_hrv: true, has_spo2: true, has_ecg: true,
    metrics_supported: ["heart_rate", "resting_heart_rate", "skin_temperature", "spo2", "steps", "sleep_duration"], source_urls: appleSources,
    editorial_note: "Larger iPhone outdoor watch; up to 42 hours, not the low-power figure. Cellular service costs extra; Apple HRV is SDNN." }),
  device({ brand: "Google", model: "Fitbit Air", category: "band", price_usd: 99.99, battery_days: 7, has_skin_temp: true, has_hrv: true, has_spo2: true,
    metrics_supported: ["heart_rate", "resting_heart_rate", "skin_temperature", "spo2", "respiratory_rate", "steps", "sleep_duration"],
    source_urls: ["https://store.google.com/us/product/google_fitbit_air_specs?hl=en-US", "https://store.google.com/us/product/google_fitbit_air?hl=en-US", googleVitals],
    editorial_note: "Screen-free tracking on iOS or Android; Google Health app required. Premium coaching is optional." }),
  device({ brand: "Google", model: "Pixel Watch 5 (41 mm, Wi-Fi)", category: "watch", price_usd: 399.99, battery_days: 1.25, has_screen: true, has_skin_temp: true, has_hrv: true, has_spo2: true, has_ecg: true,
    metrics_supported: ["heart_rate", "resting_heart_rate", "skin_temperature", "spo2", "steps", "sleep_duration"],
    source_urls: ["https://store.google.com/product/pixel_watch_5?hl=en-US", "https://store.google.com/de/product/pixel_watch_5_specs?hl=de", googleVitals],
    editorial_note: "Android watch; 41 mm model has up to 30 hours with always-on display. Premium coaching is optional; ECG is region-limited." }),
  device({ brand: "Fitbit", model: "Charge 6", category: "band", battery_days: 7, has_screen: true, has_skin_temp: true, has_hrv: true, has_spo2: true, has_ecg: true,
    metrics_supported: ["heart_rate", "resting_heart_rate", "skin_temperature", "spo2", "steps", "sleep_duration"],
    source_urls: ["https://store.google.com/us/product/fitbit_charge_6_specs?hl=en-US", googleVitals],
    editorial_note: "Compact tracker with a screen and region-limited ECG; Google account required. Current purchase price not verified." }),
  device({ brand: "Garmin", model: "Venu 4 (45 mm)", category: "watch", price_usd: 549.99, battery_days: 12, has_screen: true, has_skin_temp: true, has_hrv: true, has_spo2: true, has_ecg: true,
    metrics_supported: ["heart_rate", "skin_temperature", "spo2", "respiratory_rate", "sleep_duration"], source_urls: [garminComparison, "https://www8.garmin.com/manuals/webhelp/GUID-2CF5620C-E585-4E0A-9CC3-9565533EEE4D/EN-US/GUID-6335963E-C254-4239-9450-A0212850F303.html"],
    editorial_note: "Fitness-focused iOS/Android option; up to 12 days with always-on display off. ECG is age- and region-limited." }),
  device({ brand: "Garmin", model: "Forerunner 970", category: "watch", price_usd: 749.99, battery_days: 15, has_screen: true, has_skin_temp: true, has_hrv: true, has_spo2: true, has_ecg: true,
    metrics_supported: ["heart_rate", "skin_temperature", "spo2", "sleep_duration"], source_urls: [garminComparison, "https://www.garmin.com/en-US/newsroom/press-release/sports-fitness/garmin-unveils-the-forerunner-570-and-forerunner-970-its-newest-gps-running-and-triathlon-smartwatches-for-performance-driven-athletes/"],
    editorial_note: "Running and triathlon watch; up to 15 days in smartwatch mode, less with GPS. ECG availability varies." }),
  device({ brand: "Garmin", model: "fēnix 8 (47 mm, AMOLED)", category: "watch", battery_days: 16, has_screen: true, has_hrv: true, has_spo2: true, has_ecg: true,
    metrics_supported: ["heart_rate", "spo2", "sleep_duration"], source_urls: ["https://www.garmin.com/en-GB/p/pn/010-02904-11/", "https://www8.garmin.com/manuals/webhelp/GUID-EECCAC99-90D6-4AB1-9A3A-EC433D3365E2/EN-US/GUID-40B16F18-75A1-4B3E-8F1A-AB4919BC9E51.html"],
    editorial_note: "Previous-generation outdoor option; up to 16 days with gesture display, 7 always-on. Current price not verified." }),
  device({ brand: "WHOOP", model: "5.0 with Peak (annual plan)", category: "band", price_usd: 239, battery_days: 14, has_skin_temp: true, has_hrv: true, has_spo2: true,
    subscription_required: true, subscription_cost: "US$239 per year, including the 5.0 device; not a one-off hardware price.", metrics_supported: ["heart_rate", "resting_heart_rate", "skin_temperature", "spo2", "respiratory_rate", "sleep_duration"],
    source_urls: ["https://www.whoop.com/us/en/peak/", "https://support.whoop.com/s/article/Membership-Pricing", "https://support.whoop.com/s/article/WHOOP-Health-Monitor-Report?language=en_US"],
    editorial_note: "Screen-free recovery band with a recurring membership; 14+ days. This 5.0/Peak bundle is not the MG ECG model." }),
  device({ brand: "Oura", model: "Ring 5 (Black)", category: "ring", price_usd: 399, battery_days: 9, has_skin_temp: true, has_hrv: true, has_spo2: true,
    subscription_required: true, subscription_cost: "Full insights: US$5.99/month or US$69.99/year before US tax; regional rates differ. Limited scores and CSV export remain without membership.",
    metrics_supported: ["heart_rate", "skin_temperature", "spo2", "respiratory_rate", "sleep_duration"], source_urls: ["https://ouraring.com/store/rings/oura-ring-5/black", "https://ouraring.com/membership"],
    editorial_note: "Sleep-focused ring for iOS/Android; typical battery is 6–9 days depending on size and use. Full insights require membership." }),
  device({ brand: "Samsung", model: "Galaxy Watch9 (40 mm, Bluetooth)", category: "watch", price_usd: 379.99, has_screen: true, has_skin_temp: true, has_hrv: true, has_spo2: true, has_ecg: true,
    metrics_supported: ["heart_rate", "skin_temperature", "spo2", "sleep_duration"], source_urls: ["https://www.samsung.com/us/watches/galaxy-watch9/", "https://www.samsung.com/uk/business/watches/galaxy-watch/galaxy-watch9-40mm-graphite-lte-sm-l345fzkaeub/"],
    editorial_note: "Android watch; some health features require a compatible Galaxy phone and regional approval. Battery-days claim not verified." }),
  device({ brand: "Samsung", model: "Galaxy Ring", category: "ring", battery_days: 7, has_skin_temp: true, has_hrv: true, has_spo2: true,
    metrics_supported: ["heart_rate", "skin_temperature", "spo2", "sleep_duration"], source_urls: ["https://www.samsung.com/us/rings/galaxy-ring/", "https://www.samsung.com/us/support/answer/ANS10003282/", "https://www.samsung.com/ae/support/mobile-devices/how-can-i-measure-sleep-features-with-the-galaxy-ring/"],
    editorial_note: "Samsung/Android sleep companion; up to 7 days varies by ring size. The charging case is not counted in battery life." }),
  device({ brand: "Amazfit", model: "Active 2 (Round, standard)", category: "watch", price_usd: 99.99, battery_days: 10, has_screen: true, has_skin_temp: true, has_hrv: true, has_spo2: true,
    metrics_supported: ["heart_rate", "skin_temperature", "spo2", "respiratory_rate", "sleep_duration"], source_urls: ["https://us.amazfit.com/products/active-2-round", "https://us.amazfit.com/pages/fitness-health-tracking"],
    editorial_note: "Lower-cost screen option with iOS/Android Zepp app; up to 10 days typical use, 5 with heavy use." }),
  device({ brand: "Amazfit", model: "Balance 2", category: "watch", price_usd: 299.99, battery_days: 21, has_screen: true, has_skin_temp: true, has_hrv: true, has_spo2: true,
    metrics_supported: ["heart_rate", "skin_temperature", "spo2", "sleep_duration"], source_urls: ["https://us.amazfit.com/products/balance-2", "https://us.amazfit.com/pages/fitness-health-tracking", "https://support.amazfit.com/en/amazfit_balance_2/files/user-manual.pdf.pdf"],
    editorial_note: "Longer-battery multisport screen option; up to 21 days typical use. The core Zepp app is free." }),
  device({ brand: "Noise", model: "ColorFit Icon Buzz", category: "watch", price_inr: 1499, battery_days: 7, has_screen: true, has_spo2: true,
    metrics_supported: ["heart_rate", "spo2", "sleep_duration"], source_urls: ["https://www.gonoise.com/products/noise-noisefit-icon-buzz-smartwatch/1000"],
    editorial_note: "Budget Indian-market watch; listed sale price and up to 7 days. Check export availability before buying for HMS." }),
  device({ brand: "Ultrahuman", model: "Ring AIR", category: "ring", battery_days: 6, has_skin_temp: true, has_hrv: true, has_spo2: true,
    metrics_supported: ["heart_rate", "skin_temperature", "spo2", "sleep_duration"], source_urls: ["https://www.ultrahuman.com/us/ring/buy/better-help/"],
    editorial_note: "Screen-free ring; 4–6 days per charge. Partner offer is not a general retail price; confirm regional availability and optional services." }),
  device({ brand: "Withings", model: "Body Smart", category: "scale", price_usd: 129.95, has_screen: true,
    metrics_supported: ["weight_kg", "body_fat_pct", "heart_rate"], source_urls: ["https://www.withings.com/en-us/products/body-smart-black"],
    editorial_note: "Wi-Fi scale for weight and body-composition estimates; replaceable batteries average 15 months. Withings+ is optional." }),
  device({ brand: "Omron", model: "Evolv BP7000", category: "bp_cuff", has_screen: true,
    metrics_supported: ["blood_pressure_systolic", "blood_pressure_diastolic", "heart_rate"], source_urls: ["https://omronhealthcare.com/products/evolv-wireless-upper-arm-blood-pressure-monitor-bp7000", "https://omronhealthcare.com/storage/pdfs/evolv-wireless-upper-arm-blood-pressure-monitor-bp7000-im-en03022020.pdf"],
    editorial_note: "Upper-arm cuff with Bluetooth; four AAA batteries rated for about 300 measurements, not a fixed number of days. Check cuff fit." }),
  device({ brand: "Abbott", model: "FreeStyle Libre 3 Plus", category: "cgm", metrics_supported: ["blood_glucose"],
    source_urls: ["https://www.support.freestyle.abbott/hc/en-us/articles/27194037430161-What-is-the-FreeStyle-Libre-3-Plus-sensor", "https://www.freestyle.abbott/us-en/what-is-cgm.html"],
    editorial_note: "Interstitial-glucose sensor with up to 15 days of wear, not a rechargeable tracker. Discuss suitability with your clinician; no direct HMS connection." }),
];
