import Link from "next/link";
export default function TermsPage() {
  return <main className="onboarding stack"><h1 className="page-title">Terms of use</h1>
    <p className="muted">Version 2026-09-08. Development-preview terms pending legal review</p>
    <section className="card stack"><h2>Purpose and limits</h2><p>HMS organises personal health history and facilitates sharing with a care team. It is not a medical device and does not diagnose conditions, provide medical advice or guarantee the accuracy or completeness of device readings. Read the <Link className="underline" href="/legal/disclaimer">health disclaimer</Link>.</p>
      <p>HMS is not for emergencies. Notifications and consultations can be delayed or unavailable. If you feel unwell or need urgent help, contact your doctor or local emergency services. Do not wait for this app.</p></section>
    <section className="card stack"><h2>Accounts, guardians and information</h2><p>You must be at least 18 to create an account. Supply accurate information, protect your sign-in links, and upload only data you own or are authorised to manage. Do not impersonate a doctor or another person.</p>
      <p>Minors use guardian-owned dependent profiles without a login. Guardians are responsible for appropriate authority and consent. The build supports transfer to the dependent’s normal account at 18 or later; it does not automatically transfer ownership on a birthday. Parental verification requires approval before real minors use the service.</p>
      <p>Do not upload unlawful content, malicious files or other people’s confidential records without authority. You control sharing scopes and can withdraw ordinary doctor/caregiver access. Downloaded copies cannot be recalled. The <Link className="underline" href="/legal/privacy">privacy notice</Link> explains export, consent and deletion.</p></section>
    <section className="card stack"><h2>Doctors and consultations</h2><p>HMS is a facilitator. The intended service is consultation with independent registered medical practitioners in India; clinicians remain responsible for their professional decisions and applicable practice requirements. A registration badge is not an endorsement or a guarantee of an outcome.</p>
      <p>Profiles labelled “Sample data” are fictional demonstrations, not available clinicians. The preview has no payment collection, guaranteed availability, prescribing service or built-in video service. A clinician may supply an external Meet or Zoom link. Any real service, cross-border eligibility, charges, cancellation and refund terms need to be confirmed before a paid consultation is offered.</p></section>
    <section className="card stack"><h2>External services and availability</h2><p>Device comparisons are dated editorial information, not a guarantee of compatibility or a recommendation to buy. Check the manufacturer’s current country-specific features and terms. Pharmacy search links are optional external links, not prescriptions or product recommendations. HMS does not place orders or share health records through them.</p>
      <p>The preview may be interrupted or changed. Keep an export of records you need. No term excludes rights or liabilities that cannot lawfully be excluded.</p></section>
    <section className="card stack"><h2>Operator and governing law</h2><p>The operator’s legal identity, address, support contact and grievance process must be published before public launch. These terms are intended to be governed by Indian law, subject to mandatory protections and applicable court jurisdiction. A specific forum and international-user terms require counsel; this preview does not invent a legal entity or an exclusive court clause.</p></section>
  </main>;
}
